# Generated by Django 5.2.8 on 2025-11-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('text', 'Texte'), ('video', 'Vidéo'), ('mix', 'Texte + Vidéo')], default='text', max_length=10)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('text', models.TextField(blank=True, default='', max_length=500)),
                ('postit_color', models.CharField(default='#FFF59D', max_length=7)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
