# Generated by Django 5.2.8 on 2025-11-08 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='testimony',
            name='font_family',
            field=models.CharField(blank=True, default='Inter, sans-serif', max_length=60),
        ),
        migrations.AddField(
            model_name='testimony',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='testimony',
            name='title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='testimony',
            name='verification_type',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Téléphone')], default='email', max_length=10),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='postit_color',
            field=models.CharField(default='#FFF6D9', max_length=7),
        ),
        migrations.CreateModel(
            name='TestimonyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='testimonies/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('testimony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='wall.testimony')),
            ],
        ),
    ]
