# Generated by Django 5.2.8 on 2025-11-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_testimony_email_testimony_font_family_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimony',
            name='font_family',
        ),
        migrations.RemoveField(
            model_name='testimony',
            name='postit_color',
        ),
        migrations.AddField(
            model_name='testimony',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='kind',
            field=models.CharField(choices=[('text', 'text'), ('video', 'video'), ('mix', 'mix')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='verification_type',
            field=models.CharField(choices=[('email', 'email'), ('phone', 'phone'), ('both', 'both')], default='email', max_length=10),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
