# Generated by Django 5.2.8 on 2025-11-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0003_remove_testimony_font_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='font_family',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='testimony',
            name='postit_color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
