# Generated by Django 5.2.8 on 2025-11-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0004_testimony_font_family_testimony_postit_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'code'], name='wall_verifi_email_b0915c_idx')],
            },
        ),
    ]
