# Generated by Django 5.2.8 on 2025-11-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0005_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='testimonies/videos/'),
        ),
    ]
