# Generated by Django 5.2.8 on 2025-11-13 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0006_testimony_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonyAmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default='', max_length=64)),
                ('user_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('testimony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amen_entries', to='wall.testimony')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('session_key__gt', '')), fields=('testimony', 'session_key'), name='unique_amen_per_session'), models.UniqueConstraint(condition=models.Q(('user_email__gt', '')), fields=('testimony', 'user_email'), name='unique_amen_per_email')],
            },
        ),
    ]
